### ISSUE TITLE
Typo in blog for using gcount

### ISSUE THREAD

**Issue by wiremoons** [oneness/gcount#1]
Hi

Thanks for sharing your program — I am just starting to learn Clojure so was interested to play about with it. 

I noticed there is a typo in the 'one liner' on your blog page. To fix it, the `:` needs to be replaced with a `/` between `.com` and `oneness`. So should be:

```
git clone git@github.com/oneness/gcount.git && cd gcount && lein repl
```

Thought it maybe useful to others who might be following your blog instructions :)

Cheers

Simon

**Comment by oneness** [comment]
Hi, 
Thanks for reporting. I somehow missed the issue notice by github.  I pushed the changes and the one liner should work now.  Will close once either you or I confirm soon.

**Comment by oneness** [comment]
I just verified that it is live and thus closing this issue.
